### PR TITLE
Ab wheat nutshell

### PR DESCRIPTION
**Pull request by AliAbdulle**
# Description

Please check my apiMaganer calls. I created fetch call for all features for CRUD function. Also, i add database to run my fetch call.

Applies to issue # 3

## Type of change

Please delete options that are not relevant.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# Testing Instructions

Use the following steps:
git fetch --all
run json server
run npm start

use this database

    "events": [
        {
            "id": 1,
            "name": "NFL Draft",
            "date": "22/4/2019",
            "location": "100 Main street"
          },
          {
            "id": 2,
            "name": "Wedding",
            "date": "2/4/2019",
            "location": "21 Church street Plvd"
          }

# Checklist:

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings or errors
- [ ] I have added test instructions that prove my fix is effective or that my feature works

### CODE REVIEW

**Review by Theskiman — DISMISSED** [review]
Fetch calls all worked as expected.

**Review by JJHibray — DISMISSED** [review]
calls work

**Review by Theskiman — APPROVED** [review]
Everything worked as expected

**Review by JJHibray — APPROVED** [review]
looks good

**Pull request merged**
